import './globals.css'
import { Barlow_Semi_Condensed as BarlowSemiCondensed } from 'next/font/google'

const barlow = BarlowSemiCondensed({
  subsets: ['latin'],
  variable: ['--font-barlow'],
  weight: ['500', '600'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${barlow.variable} font-barlow`}>{children}</body>
    </html>
  )
}
